//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Att
    {
        public int Id { get; set; }
        public int Class { get; set; }
        public int Attend { get; set; }
        public int Absent { get; set; }
    }
}
