//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Overtimehr { get; set; }
        public Nullable<decimal> Totalfees { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
    }
}
