//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1 : DbContext
    {
        public Model1()
            : base("name=Model1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Att> Atts { get; set; }
        public virtual DbSet<Father> Fathers { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<Mother> Mothers { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Stud> Studs { get; set; }
        public virtual DbSet<Fee1> Fee1 { get; set; }
    }
}
