//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stud
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Mykid { get; set; }
        public string Health { get; set; }
        public string TotalFees { get; set; }
        public string Overmin { get; set; }
        public string Statuspay { get; set; }
        public string Datepay { get; set; }
        public string Monthpay { get; set; }
        public string DateAttend { get; set; }
        public string StatusAttend { get; set; }
    }
}
